# The build part for Netlify with a Nuxt project
[build]
    base='/'
    publish='.output'
    command='npm run go'
    environment = { NODE_VERSION = "18.0.0" }

# Also put headers
[[headers]]
    for = "/*"

    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        cache-control = "public, max-age=10000, must-revalidate"